name: Build kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt update && sudo apt install build-essential gcc-arm-none-eabi cmake
    - name: Build
      run: cd sources && ./build.sh
